<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FA2GR7UQ" failures="1" tests="2" name="john" time="4.934" errors="0" timestamp="2024-02-20T20:58:03 IST">
  <testcase classname="com.seldocker.Test.VendorPortalTest" name="loginPage" time="1.316"/>
  <testcase classname="com.seldocker.Test.VendorPortalTest" name="dashBoardTest" time="2.792">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at com.seldocker.Test.VendorPortalTest.dashBoardTest(VendorPortalTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashBoardTest -->
</testsuite> <!-- john -->
